# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-24 11:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('query', models.CharField(max_length=250, verbose_name='query')),
                ('social_plugin', models.CharField(choices=[('edsa_twitter', 'Twitter'), ('edsa_instagram', 'Instagram'), ('edsa_facebook_fanpage', 'Facebook Fanpage'), ('edsa_wordpress_rss', 'Wordpress RSS'), ('edsa_youtube_search', 'Youtube search')], max_length=250, verbose_name='social plugin')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'aggregator',
                'verbose_name_plural': 'aggregators',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'feed',
                'verbose_name_plural': 'feeds',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('short_description', models.TextField(blank=True, verbose_name='short description')),
                ('media_url', models.URLField(blank=True, max_length=500, verbose_name='media url')),
                ('media_url_type', models.CharField(blank=True, choices=[('url', 'url'), ('image', 'image'), ('video', 'video')], max_length=100, verbose_name='media url type')),
                ('priority', models.IntegerField(default=100, verbose_name='display priority')),
                ('activate', models.BooleanField(default=False, verbose_name='activate')),
                ('author', models.CharField(max_length=250, verbose_name='author')),
                ('language', models.CharField(blank=True, max_length=2, verbose_name='language')),
                ('resource_date', models.DateTimeField(verbose_name='resource date')),
                ('social_id', models.CharField(blank=True, max_length=250, verbose_name='social_id')),
                ('social_type', models.CharField(choices=[('edsa_article', 'Article'), ('edsa_twitter', 'Twitter'), ('edsa_instagram', 'Instagram'), ('edsa_facebook_fanpage', 'Facebook Fanpage'), ('edsa_wordpress_rss', 'Wordpress RSS'), ('edsa_youtube_search', 'Youtube search')], default='edsa_article', max_length=250, verbose_name='social plugin')),
                ('query', models.CharField(blank=True, max_length=250, verbose_name='query')),
                ('favorite', models.BooleanField(default=False, verbose_name='favorite')),
                ('view_size', models.CharField(choices=[('default', 'default'), ('xsmall', 'Xsmall'), ('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('xlarge', 'Xlarge')], default='default', max_length=100, verbose_name='view size')),
                ('text_display', models.CharField(choices=[('default', 'default'), ('bottom', 'bottom'), ('top', 'top')], default='default', max_length=100, verbose_name='text display')),
                ('button_label', models.CharField(blank=True, max_length=100, verbose_name='button label')),
                ('button_color', models.CharField(choices=[('white', 'white'), ('black', 'black'), ('primary', 'primary'), ('secondary', 'secondary'), ('tertiary', 'tertiary')], default='black', max_length=100, verbose_name='button color')),
                ('background_color', models.CharField(blank=True, max_length=250, verbose_name='background color')),
                ('new_page', models.BooleanField(default=False, verbose_name='open in new page')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date')),
                ('update_date', models.DateTimeField(default=None, verbose_name='update date')),
                ('updated', models.BooleanField(default=False, verbose_name='updated')),
                ('feeds', models.ManyToManyField(to='socialaggregator.Feed', verbose_name='feeds')),
                ('image', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_image', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('thumbnail', filer.fields.image.FilerImageField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_thumbnail', to=settings.FILER_IMAGE_MODEL, verbose_name='thumbnail')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
                'ordering': ('-priority', 'name'),
            },
        ),
        migrations.AddField(
            model_name='aggregator',
            name='feeds',
            field=models.ManyToManyField(to='socialaggregator.Feed', verbose_name='feeds'),
        ),
    ]
